version: "3.8"
services:
  app:
    build: ./app
    networks:
      - app-net
  proxy:
    build: ./proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - app-net

networks:
  app-net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.32.0/24
          ip_range: 10.0.32.0/28