version: "3.8"
services:
  web-app:
    build: ./web-app
    environment:
      HOST_NAME: $HOSTNAME
    networks:
      - app-net
  proxy:
    build: ./proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - app-net
      - dmz-net

networks:
  app-net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.32.0/24
          ip_range: 10.0.32.0/28
  dmz-net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.33.0/24
          ip_range: 10.0.33.0/28